language: python
env:
 - PIP_CONFIG_FILE=pip.conf
python:
 - "2.6"
 - "2.7"
install:
 - pip install -r requirements.txt
 - pip install scripttest
script: nosetests
before_install:
 - sudo modprobe snd-dummy
 - sudo apt-get install portaudio19-dev python-dev alsa-utils
